---
title: "title"
author: "Chuck Boecking"
date: 2024-05-31
tags: [developer,sql,ai,llm,cli,operations,workflow,example]
type: blog
audience: [cio,coo,cto,ceo,technician,developer,accounting]
published: false
---
